[package]
name = "aoc2018"
version = "0.1.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
nalgebra = "*"
num = "*"
failure = "*"
chrono = "*"
hashbrown = "*"
itertools = "*"
