[package]
name = "aoc2018"
version = "0.1.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
nalgebra = "0.19.0"
num = "0.2.0"
chrono = "0.4.10"
hashbrown = "0.6.3"
itertools = "0.8.2"
rayon = "1.2.1"
ncurses = "5.99.0"
anyhow = "1.0.25"